name: PermissionsTime
main: gg.frog.mc.permissionstime.PluginMain
version: 0.0.1
author: GeekFrog

commands:
    permissionstime:
        description: Show all commands.

permissions:
    permissionstime.reload:
        description: Reloads the config file.
        default: false