name: PermissionsTime
main: gg.frog.mc.permissionstime.PluginMain
version: 0.0.1
author: GeekFrog
softdepend: [SQLibrary, Vault]

commands:
    permissionstime:
        description: Show all commands.

permissions:
    permissionstime.*:
        description: Gives access to all PermissionsTime commands.
        children:
            permissionstime.me: true
            permissionstime.reload: true
            permissionstime.give: true
            permissionstime.set: true
            permissionstime.remove: true
            permissionstime.packages: true
            permissionstime.reload: true
    permissionstime.me:
        description: View himself package.
        default: true
    permissionstime.reload:
        description: Reloads the config file.
        default: op
    permissionstime.give:
        description: Give player package <time>day.
        default: op
    permissionstime.set:
        description: Set player package <time>day.
        default: op
    permissionstime.remove:
        description: Remove player package.
        default: op
    permissionstime.packages:
        description: View packages.
        default: op
        